/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.Conexion;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pais;
import modelo.Paquete;

/**
 *
 * @author Adriana
 */
public class FrmPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPaquete
     */
    int perSeleccion = 0;
    public FrmPaquete() {
        initComponents();
        cargarDatos();
        CargarPais();
        CargarHotel();
        CargarAerolinea();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquete = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cbPais = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JFormattedTextField();
        txtNumDias = new javax.swing.JFormattedTextField();
        cbHotel = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbAerolinea = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setClosable(true);

        tablaPaquete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Paquete", "Descripción", "País", "Precio", "Número De Días", "Hotel", "Aerolinea"
            }
        ));
        tablaPaquete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPaqueteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPaquete);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANTENIMIENTO PAQUETES");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precio");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("País");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número De Días");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });

        txtNumDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNumDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumDiasKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Aerolínea");
        jLabel7.setToolTipText("");

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btninsert.png"))); // NOI18N
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEdit.png"))); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnclean.png"))); // NOI18N
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnDelete.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(43, 43, 43))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(82, 82, 82)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(20, 20, 20)
                                .addComponent(txtNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEditar)
                    .addComponent(btnInsertar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        Paquete p = new Paquete();
        p.setDescripcion(txtDescripcion.getText());
        //p.setCodPais(); = String.valueOf(cbPais.getSelectedItem());
        //p.setCodPais(cbPais.getSelectedIndex());
        //p.setCodPais(cbPais.getSelectedIndex());
        p.setCodPais(Integer.parseInt(cbPais.getSelectedItem().toString()));
        p.setPrecio(Double.parseDouble(txtPrecio.getText()));
        p.setNumDias(Integer.parseInt(txtNumDias.getText()));
        //p.setCodHotel(cbHotel.getSelectedIndex());
        p.setCodHotel(Integer.parseInt(cbHotel.getSelectedItem().toString()));
        //p.setCodAerolinea(cbAerolinea.getSelectedIndex());
        p.setCodAerolinea(Integer.parseInt(cbAerolinea.getSelectedItem().toString()));
        p.insertarPaquete(p);
        limpiar();
        cargarDatos();
        CargarAerolinea();
        CargarPais();
        CargarHotel();
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        Paquete p = new Paquete();
        p.setDescripcion(txtDescripcion.getText());
        p.setCodPais(Integer.parseInt(cbPais.getSelectedItem().toString()));
        p.setPrecio(Double.parseDouble(txtPrecio.getText()));
        p.setNumDias(Integer.parseInt(txtNumDias.getText()));
        p.setCodHotel(Integer.parseInt(cbHotel.getSelectedItem().toString()));
        p.setCodAerolinea(Integer.parseInt(cbAerolinea.getSelectedItem().toString()));
        p.setCodPaquete(perSeleccion);
        int dialogResult = JOptionPane.showConfirmDialog(null, "Esta seguro de Editar este Pais", "Agencia de Viajes", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            p.editarPaquete(p);
            limpiar();
            cargarDatos();
            CargarAerolinea();
            CargarHotel();
            CargarPais();
        } else {
            limpiar();
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        Paquete paq = new Paquete();
        int dialogResult = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este paquete", "Agencia de Viajes", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            paq.eliminarPaquete(perSeleccion);
            limpiar();
            cargarDatos();
            CargarAerolinea();
            CargarHotel();
            CargarPais();
        } else {
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked
    
    private void limpiar() {
        txtDescripcion.setText("");
        cbPais.setSelectedItem(0);
        txtPrecio.setText("");
        txtNumDias.setText("");
        cbHotel.setSelectedItem(0);
        cbAerolinea.setSelectedItem(0);        
        perSeleccion = 0;
    }
    
    public void cargarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaPaquete.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        Object Fila[] = new Object[tablaPaquete.getColumnCount()];
        Paquete p = new Paquete();
        for (Paquete pqu : p.mostrarPaquete()) {
            Fila[0] = pqu.getCodPaquete();
            Fila[1] = pqu.getDescripcion();
            Fila[2] = pqu.getCodPais();
            Fila[3] = pqu.getPrecio();
            Fila[4] = pqu.getNumDias();
            Fila[5] = pqu.getCodHotel();
            Fila[6] = pqu.getCodAerolinea();            
            modelo.addRow(Fila);
        }
        tablaPaquete.setModel(modelo);        
        
    }
    
    public void CargarPais() {
        try
        {
        Conexion cone = new Conexion();
                String sql = "select * from tb_pais";
                ResultSet rs = cone.consultar(sql);
            while(rs.next()){                            
                cbPais.addItem(rs.getString(1));
            }
            cone.desconectar();
            }
        catch(Exception e)
        {
            System.out.println("Error"+e);
        }    
    }
    
    public void CargarHotel() {
        try
        {
        Conexion cone = new Conexion();
                String sql = "select * from tb_hotel";
                ResultSet rs = cone.consultar(sql);
            while(rs.next()){                            
                cbHotel.addItem(rs.getString(1));
            }
            cone.desconectar();
            }
        catch(Exception e)
        {
            System.out.println("Error"+e);
        }    
    }
    
    public void CargarAerolinea() {
        try
        {
        Conexion cone = new Conexion();
                String sql = "select * from tb_aerolinea";
                ResultSet rs = cone.consultar(sql);
            while(rs.next()){                            
                cbAerolinea.addItem(rs.getString(1));
            }
            cone.desconectar();
            }
        catch(Exception e)
        {
            System.out.println("Error"+e);
        }    
    }
    
    private void tablaPaqueteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPaqueteMouseClicked
        txtDescripcion.setText(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 1).toString());
        cbPais.setSelectedItem(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 2).toString());
        txtPrecio.setText(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 3).toString());
        txtNumDias.setText(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 4).toString());
        cbHotel.setSelectedItem(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 5).toString());
        cbAerolinea.setSelectedItem(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 6).toString());        
        perSeleccion = Integer.parseInt(tablaPaquete.getValueAt(tablaPaquete.getSelectedRow(), 0).toString());
    
    }//GEN-LAST:event_tablaPaqueteMouseClicked

    private void txtNumDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumDiasKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumDiasKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbAerolinea;
    private javax.swing.JComboBox<String> cbHotel;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPaquete;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JFormattedTextField txtNumDias;
    private javax.swing.JFormattedTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
